INSERT INTO ACTOR(FIRST_NAME, LAST_NAME, DATE_OF_BIRTH) VALUES ('Margot', 'Robbie', '1990-07-02');
INSERT INTO ACTOR(FIRST_NAME, LAST_NAME, DATE_OF_BIRTH) VALUES ('Cilian', 'Murphy', '1976-05-25');
INSERT INTO ACTOR(FIRST_NAME, LAST_NAME, DATE_OF_BIRTH) VALUES ('Leonardo', 'DiCaprio', '1974-11-11');
INSERT INTO ACTOR(FIRST_NAME, LAST_NAME, DATE_OF_BIRTH) VALUES ('Ryan', 'Gosling', '1980-11-12');

INSERT INTO MOVIE(TITLE, CATEGORY, PREMIERE_DATE) VALUES ('BARBIE', 'COMEDY', '2023-07-21');
INSERT INTO MOVIE(TITLE, CATEGORY, PREMIERE_DATE) VALUES ('OPPENHEIMER', 'DRAMA', '2023-07-21');
INSERT INTO MOVIE(TITLE, CATEGORY, PREMIERE_DATE) VALUES ('WILK Z WALLSTREET', 'COMEDY', '2013-12-17');

INSERT INTO MOVIE_ACTORS(ACTORS_ID, MOVIES_ID) VALUES (1, 1);
INSERT INTO MOVIE_ACTORS(ACTORS_ID, MOVIES_ID) VALUES (1, 3);
INSERT INTO MOVIE_ACTORS(ACTORS_ID, MOVIES_ID) VALUES (2, 2);
INSERT INTO MOVIE_ACTORS(ACTORS_ID, MOVIES_ID) VALUES (3, 2);
INSERT INTO MOVIE_ACTORS(ACTORS_ID, MOVIES_ID) VALUES (3, 3);
INSERT INTO MOVIE_ACTORS(ACTORS_ID, MOVIES_ID) VALUES (4, 1);